### ISSUE TITLE
[PROD] Move Territories to DB

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#130]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

# Problem
Territories are currently exclusively on the DEI, which is not scalable.

# Objectives
To have access to PLD's territories in a more flexible way. 
It may be used by
- Public API
- BO

# Proposed solution

- [x] Move the Territories on DEI (Global tab) to the DB using the Territories JSON schema
- [ ] Create an API Endpoint to extract Territories (#304)
- [ ] Document the Model and Endpoint (#299)

# Extra information
- Must have
 -- Must follow Territory Schema: https://theiofoundation.stoplight.io/docs/projectlockdown/API/Reference/Project-Lockdown.v1.json/components/schemas/Territory
  -- API Endpoint should allow to extract Territories with a start Territory code + a "depth" 
   https://theiofoundation.stoplight.io/docs/projectlockdown/API/Reference/Project-Lockdown.v1.json/paths/~1Territories/get

- Should have
 -- 

- Could have
 -- Other API Endpoint params possible. Please propose.

- Won't have
 -- 

# Resources
## Technical documentation
- Territory JSON Schema (Model)
  https://theiofoundation.stoplight.io/docs/projectlockdown/API/Reference/Project-Lockdown.v1.json/components/schemas/Territory

- API Endpoint
  https://theiofoundation.stoplight.io/docs/projectlockdown/API/Reference/Project-Lockdown.v1.json/paths/~1Territories/get

## UXUI resources
Nil 

## Other documentation resources

# Tests
Nil

# Related Issues

**Comment by daphnecys** [comment]
Which Definition should I refer to for Territories? https://theiofoundation.stoplight.io/docs/projectlockdown/API/Reference/Project-Lockdown.v1.json/components/schemas/Territory  This is marked as ???DEPRECATED? but it is still referred to in DataSetLayer https://theiofoundation.stoplight.io/docs/projectlockdown/API/Reference/Project-Lockdown.v1.json/components/schemas/DataSetLayer

**Comment by jeff-knurek** [comment]
As discussed in slack, going to break this ticket down into 3, with the first of the work already done in https://github.com/TheIOFoundation/ProjectLockdown/pull/217
