### ISSUE TITLE
[PROD] Update text on MAP (tab menu)

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#14]
@tiof-pld-team-documentation
**Problem**
The current contents on the MAP tab menu is not current.

**Objectives**
Rewrite the contents to reflect the new multi-DSL approach of v2.0:
- General information is to be provided by the website.
- Each DSL is self-contained in its MAP representation, including data and all other necessary information such as data points description, methodology, etc.

**Extra information**

* This image provides views of where the "tab menu" is located on the map, and how it looks in it's different open states:
https://user-images.githubusercontent.com/9198668/100940664-57f1ca00-3533-11eb-9827-a604e122ad91.png

* The data from the API will provide doc links under the URLDOCS attribute
	https://theiofoundation.stoplight.io/docs/projectlockdown/API/Reference/Project-Lockdown.v1.json/components/schemas/

* These doc links will be to json files. The json files will be translated to different languages by POEditor. They will likely be version controlled in this repo: https://github.com/TheIOFoundation/ProjectLockdown.DataSetLayers but it's possible that they will be hosted in Azure storage bucket and hosted under CDN https://docs.microsoft.com/en-us/azure/storage/blobs/static-website-content-delivery-network

**Pending**

**Related Issues**

**Comment by jeff-knurek** [comment]
**as per discussion:**
the content of the text for the (tab menu) along with the i18n library will just be copied over to v2.0

the future work for using POEditor for translation is dependant on https://github.com/TheIOFoundation/ProjectLockdown/issues/86

**Comment by jeff-knurek** [comment]
after some discussions of the current state, what the scope of this task is, and what is still needed to be done - I'm going to close this task. 

right now the text is contained in language specific json files. the react module gets this text via key/values, which aligns well with being able to get the correct text based on API response. we still have only 1 DSL and so there's use of the API Environment info at the moment to switch the text, but that should be straight forward to fix. we still need to look into how POEditor will work with regard to #86
