### ISSUE TITLE
[ADM] Meeting Minutes: 

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#154]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

**Quicktips**
ℹ Check pending topics by filtering Issues by "📋 Flag: Next Meeting" + other necessary filters (such as your own Team for instance).
🎥 Call recording link: 

# Objectives
Initial call (Part B) for Team Devs to get to know everyone, their skills & motivations and get started with tasks from now on.

# Attending
- @filipkowal
- @jeff-knurek 
- @ColisaNo195 
- Salocin
- @JFQueralt 
- @jeremy0ng 
- Paul Karikari

# Minutes
- Session being recorded - Consent given by all attendees
- Introductions from all members.
- Brief comments on PLD objectives.
- Mentions on TechUp (coming and following)
- Invitation to participate to other meetings in the project.
- Adding internal calendars.

Notes: If anything is missing or is incorrect please make a mention on the Issue.

# Next Steps
@JFQueralt to introduce to @jeff-knurek 
- [x] Mapbox

Onboard to GitHub teams
- [x] Salocin
- [x] Paul Karikari

**Comment by jeff-knurek** [comment]
@JFQueralt checking what notification you get
