### ISSUE TITLE
[ADM] Meeting Minutes: Weekly Dev call [east] (2021-01-18)

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#163]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

**Quicktips**
ℹ Check pending topics by filtering Issues by "📋 Flag: Next Meeting" + other necessary filters (such as your own Team for instance).

🎥 Call recording link:  https://drive.google.com/file/d/1VLyX-_-kX3bUKGAk_IfOqMu59q0keM8s/view?usp=sharing

# Objectives
Weekly meeting + Updates on progress & next steps.

About TechUp:
What can we do to improve the experience / results?

# Attending
@jeff-knurek 
@daphnecys 
@sumeyyezeynepbulbul 
@SalocinDotTEN 
@jeremy0ng 
@JFQueralt 

# Minutes
Jeff welcomes to the first regular weekly meeting.

Discussion about how to approach the different levels of knowledge of the team members so that we can move forward to plan Sprints.

Mention that ZenHub allows for Due Dates.

Mentioned that we have Positions available in the repo that should allow to help us bring new members to the Team.

Individual round up
@daphnecys 
Giving feedback on what she did during the Spring (TechUp)

@jeff-knurek 
TechUp feedback, in general it was a good opportunity to learn lessons and improve in the future.
Some Tech hiccups.  Discouragement for not having that many people on Saturday.
Cleaning up tickets.

@JFQueralt 
Updated on the NDI grant. Explained some of the difficulties we went through and that we are very close to deadline with the need to finish the deliverables. Hoping to meet with Code for Africa and NDI this same week to look into options.

@jeremy0ng 
Has been getting up to speed.
Some difficulties with some platforms that we need to address.

@Kavitha78 
Agile management implementation.
Hoping for Sprint meetings asap.
Would have wanted to have more Team Members attending to the event and the Capacity Building sessions, specially those that 

@SalocinDotTEN (Nicolas Y.)
Needs more time to get acquainted to the tools and the documentation style. Would enjoy having some training on those tools (Stoplight esp.). Could not attend some parts of TechUp due to clashing with other events. But on the whole very good.

@sumeyyezeynepbulbul 
Enjoyed TechUp and the Airmeet platform. Would hope for more attendees. 
Would like to schedule a meeting for Backup & Restore strategies.

**Notes**: If anything is missing or is incorrect please make a mention on the Issue.

# Next Steps
@jeff-knurek 
- [ ] Aiming at having tickets ready 

@Isaac 
- [ ] Will be working on setting the whole sessions for the next 6 months (planning for whole year).

@Everyone
- [ ] To post on Team Devs channel about the trainings they would like to have access to.

@JFQueralt
- [X] Post the links to the rest of the sessions.
- [ ] Find trainings for the tools for everyone.
- [X] Add Zeynep to Infrastructure channel.

## When to close Meeting Issues:
- [ ] All Action Items completed
- [x] Recording link set (if applicable)

**Comment by SalocinDotTEN** [comment]
Updated a bit of my portion and corrected Airmeet spelling.

**Comment by sumeyyezeynepbulbul** [comment]
Backup & Recovery Procedures 
Necessary information to decide the correct replication region

**Comment by sumeyyezeynepbulbul** [comment]
Backup & Recovery Procedures
Necessary information to decide the correct replication region

**Comment by JFQueralt** [comment]
@sumeyyezeynepbulbul 
The Issue is not resolved yet. Any reason why you closed it?
