### ISSUE TITLE
[PROD] UI Components: Update Search (S).

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#188]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

# Problem
- The current implementation of this UI Component is made on PReact. Decision was made that the codebase should be moved to Rect.
-  The current implantation is not reusable and documentation is not self-evident.

# Objectives
- To follow the technical requirements of PLD v2.0
- To enhance reusability and documentation for the UI Component

# Proposed solution
- [x] To rebuild the UI Component in React using Storybook
- [ ] Document the UI Component

# Extra information
- Must have
 -- Rebuild the UI Component in React
 -- Store it as a Storybook story

- Should have
 -- Nil

- Could have
 -- Nil

- Won't have
 -- Nil

# Resources
## 📖 Technical documentation
* General considerations: [Project Wiki](https://github.com/TheIOFoundation/ProjectLockdown/wiki/Dev-Guidelines)
* Project Architecture: [Project Wiki](https://github.com/TheIOFoundation/ProjectLockdown/wiki/Project-Architecture)
* Data Lifecycle: [Project Wiki](https://github.com/TheIOFoundation/ProjectLockdown/wiki/Data-Lifecycle)

🔶 MAP
* Getting Started: [Project Wiki](https://github.com/TheIOFoundation/ProjectLockdown/wiki/Mapping-Platform-(MAP))
* UXUI Documentation: [Figma](https://TIOF.Click/PLDDocsMAPuxui)

## Other documentation resources

# Tests

# Related Issues

**Comment by jeff-knurek** [comment]
completed in #362
