### ISSUE TITLE
[PROBLEM] Map not showing up in the production build

### ISSUE THREAD

**Issue by Dhaiwat10** [TheIOFoundation/ProjectLockdown#209]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

---

**Describe the bug**
The map is not loading properly in the production build. Instead of the world map, you will see a blank white screen. 

**To Reproduce**
1. Create a production build of the MAP module by running `npm install` and `npm run build`.
2. Serve the production build on a local server using `serve -s build`.
3. Open the address where the build is being served in your browser.

**Expected behavior**
The map should load a simple color-coded world map instead of the white empty space.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/600935b579174e6e25510f49/03cf0cbe-2204-4e57-a3c0-6c43d343f0d2)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 88

**Additional context**
Check the error message from the mapboxgl library in the screenshot attached above.

**Comment by Dhaiwat10** [comment]
Looked around for possible solutions. Here is a Github discussion I found: https://github.com/mapbox/mapbox-gl-js/issues/10240. Tried the suggested fix and the problem is gone. Are we okay with downgrading to v1.13.0 of the mapboxgl package?

**Comment by Dhaiwat10** [comment]
Created a branch (`mapboxgl-downgrade`) containing the solution.

**Comment by jeff-knurek** [comment]
I think the downgrade is a good temporary solution. For reference, this issue https://github.com/mapbox/mapbox-gl-js/issues/10173 is the current open issue to track when the problem gets fixed upstream.

**Comment by Dhaiwat10** [comment]
Integrated the changes into the `ocg-dev-1` branch (PR #208).
