### ISSUE TITLE
[PROBLEM] Storybook errors and warnings

### ISSUE THREAD

**Issue by Dhaiwat10** [TheIOFoundation/ProjectLockdown#210]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

**Describe the bug**
Currently, some components are throwing errors when viewed in Storybook. This is happening because these components are expecting `ThemeContext` for the light/dark mode functionality (please refer `Settings.js` inside `MAP/src/components/Settings`). We need to pass this down in Storybook using decorators.

**To Reproduce**
1. Start up the Storybook server.
2. Try accessing the `Settings` component.

**Expected behavior**
The components should render without any errors or warnings.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/600935b579174e6e25510f49/0afed611-779a-44ce-9cce-953a435206b0)

**Comment by jeff-knurek** [comment]
these were addressed and I think now all storybooks are error free
