### ISSUE TITLE
[PROD] Create sample JSON for Dataset Layer structure EN v1.0 - Layouts Schema

### ISSUE THREAD

**Issue by daphnecys** [TheIOFoundation/ProjectLockdown#22]
**Problem**
We want to create sample JSONs for the Dataset Layer structure based on [TIOF] Project Lockdown [I] Dataset Layer structure EN v1.0 - https://docs.google.com/spreadsheets/d/1LyfHe2SyX1OWCnKx9DxDPlHwloOnCVjMqn33YMTwXl0/edit#gid=1697341414

Data: https://docs.google.com/spreadsheets/d/1lYi_nrtI6WHpjKSPDIa2JaN5-rhIUlxTDx0fXcGoqYk/edit?ts=5f54cb6d#gid=1404284038

**Objectives**
To verify the completeness and correctness of the defined structure. 

**Outcome**
1) JSON for the data definition
2) JSON for the data entry for at least 3 territories, with at least several data entries each.

**Extra information**
Store resulting sample JSONs in CosmosDB.
Tracking in daphne's repo: https://github.com/daphnecys/tiof-lockdown-sample-json

**Pending**

**Resources**

**Related Issues**

**Comment by jeff-knurek** [comment]
all documentation appear in Stoplight, including samples.
