### ISSUE TITLE
[PROD] Rebuild Style StatsBox (SB) desktop to look like Mobile.

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#4]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

# Problem
The current desktop visualization of the StatsBox is takes too much surface. In order to gain visual space, it is to be rendered in the same way as mobile.

# Objectives
- To standardize the user experience among platforms
- To increase the visible space in the MAP

# Proposed solution
Reuse the existing mobile design and use it on desktop too.

**Current desktop UI view**
![image](https://user-images.githubusercontent.com/9198668/94980643-1c03ae00-055e-11eb-93be-75a08196cd38.png)

**Target desktop UI view**
![image](https://user-images.githubusercontent.com/9198668/94980686-90d6e800-055e-11eb-9837-1723ba08d070.png)

**Note**
Ignore the "Lockdown" banner as it is treated on a separate Issue: https://github.com/TheIOFoundation/ProjectLockdown/issues/5

# Extra information
- Must have
 -- Same design in mobile & desktop

- Should have
 -- Nil

- Could have
 -- Nil

- Won't have
 -- Nil

# Resources
## UXUI resources
https://TIOF.Click/PLDDocsMAPUXUI

## Other documentation resources

# Tests

# Related Issues

**Comment by merchantweb** [comment]
Update made

**Comment by jeff-knurek** [comment]
update in March was to the v1.0 site code base, and was fixed in #363 for v2.0
