### ISSUE TITLE
[PROD] Convert project banner into watermark

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#5]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

# Problem
The current project banner takes up too much space for which it has no real use. See screenshot:

![image](https://user-images.githubusercontent.com/9198668/94980643-1c03ae00-055e-11eb-93be-75a08196cd38.png)

# Objectives
Following the update of Desktop version of the StatsBox (SB) (see #4 ), we would need to 

In general, we indent to:
- To reduce the visual impact of the project banner.
- To keep the project properly identified in the MAP.
 
# Proposed solution
- [ ] Design a PLD Watermark
- [ ] Incorporate the PLD Watermark in the MAP
- [ ] Give the Watermark a URL to https://ProjectLockdown.world

# Extra information
- Must have
 -- PLD Watermark to appear at all times. Possible configurations to be implemented later on.
 -- Integrate in a way that minimizes visual disturbance and avoids UX issues to the users.

- Should have
 -- Nil

- Could have
 -- Nil

- Won't have
 -- Nil

# Resources
## Other documentation resources

PLD Website:
https://ProjectLockdown.world

# Tests

# Related Issues
#4 

**Problem**

**Objectives**

Since the final mockup is still pending, the best course of action would be
- Create a text-based sample (Project Lockdown)
- Apply some basic CSS
- Position Top Left of the MAP
Once we have the final mockup we will proceed with the final retouches.

**Mockup**
![image](https://user-images.githubusercontent.com/9198668/94980842-f5467700-055f-11eb-9c13-0478d9c65527.png)

**Pending**
- Final mockup for the watermark.
@TheIOFoundation/tiof-pld-team-uxui 

**Related Issues**
Ignore the StatsBox as it is being treated in a separate Issue: https://github.com/TheIOFoundation/ProjectLockdown/issues/4

**Comment by KaylaKremer** [comment]
I'd like to work on this!
