### ISSUE TITLE
[PROD] Implement loading animation.

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#7]
**Problem**
During the load of the MAP, a number of external dependencies and data loading happen asynchronously. As a result, users experience a loading that does not properly indicate when is the information accurate and the MAP available.
From a UX perspective, this is not conducive.

**Objectives**
To create a loading Clock to signify clearly to the user that:
- The MAP is loading
- The MAP is ready
- _FUTURE_: That something has gone wrong in the loading
- _FUTURE_: That something has gone wrong in the current user interaction

**Extra information**
Since we do not have a currently a design for the Clock, for the time being just use a sample.
A good place to generate one: https://loading.io/spinner/clock/-pin-tick-clock-time-date-watch-rotate

**Pending**
For FUTURE, we are missing defining a flow.

@TheIOFoundation/tiof-pld-team-uxui 
To design a Clock.

**Resources**
- https://medium.com/flawless-app-stories/everything-you-need-to-know-about-loading-animations-10db7f9b61e
- https://codepen.io/tiagofranco/pen/mKeyt

**Related Issues**

**Comment by trevorcarter83** [comment]
@JFQueralt open for the task

**Comment by JFQueralt** [comment]
@trevorcarter83 great.
Let me know if you need anything else from us.

For refference, do check that we are transitioning from PReact to React https://github.com/TheIOFoundation/ProjectLockdown/issues/3
