### ISSUE TITLE
[PROD] Move Definition data into DB

### ISSUE THREAD

**Issue by JFQueralt** [TheIOFoundation/ProjectLockdown#97]
![logo](https://user-images.githubusercontent.com/9198668/85232285-68543380-b430-11ea-8353-1aafb79baf78.png) 

# Problem
We still have data on our initial documentation reference:
https://docs.google.com/spreadsheets/d/1LyfHe2SyX1OWCnKx9DxDPlHwloOnCVjMqn33YMTwXl0/edit?ts=5f21257e#gid=881024093

# Objectives
Move the `Definitions` info (types) to its corresponding place in the new DB.

# Proposed solution

- [ ] Declare the "Definitions" tab to the DB.
- [ ] Ensure all Definitions are reflected in the schemas and definitions on Stoplight
- [ ] Delete the spreadsheet

# Related Issues

**Comment by daphnecys** [comment]
is this duplicate of #88?

**Comment by jeff-knurek** [comment]
I've looked through this spreadsheet, and almost all the info seems to be included in the DEI doc: https://docs.google.com/spreadsheets/d/1mVyQxxLxAF3E1dw870WHXTOLgYzmumojvzIekpgvLV0/edit#gid=629188932
However there is still some useful info in the Source Types and Status Types, and so I don't want to delete the spreadsheet, but the scope of this task needs to be updated.
